
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

class JSI_EXPORT RTNContextMenuEventEmitter : public ViewEventEmitter {
public:
    using ViewEventEmitter::ViewEventEmitter;

    // 属性
    struct OnPress {
        int index;
        std::vector<int> indexPath;
        std::string name;
    };

    struct OnPreviewPress {};

    struct OnCancel {};

    // 方法
    void onContextMenuClick() const;

    void onPress(OnPress value) const;

    void onPreviewPress(OnPreviewPress value) const;

    void onCancel(OnCancel value) const;
};

} // namespace react
} // namespace facebook
